Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,10 +39,11 @@ jobs:
      
       - name: Failing step
         id: demo
-        run: exit 0
+        run: exit 1
         
       - name: The demo step has failed
-        if: ${{ failure() && steps.demo.conclusion == 'failure' }}
+        #if: ${{ failure() && steps.demo.conclusion == 'failure' }}
+        if: ${{ always() }}
         run: echo "HERE"
      
       - name: Set AWS variables
