Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,9 +3,11 @@
 name: dispatch_test
 
 env:
-      KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      DAGS: ${{ secrets.DAGS_DIR }}
+      KEY_ID:          ${{ secrets.AWS_ACCESS_KEY_ID }}
+      ACCESS_KEY:      ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      TARGET_DAGS_DIR: ${{ secrets.DAGS_DIR }}
+      SOURCE_DAGS_DIR: dags
+      S3_BUCKET_NAME:  andydagsbucket
       
 # Controls when the workflow will run
 on:
@@ -48,12 +50,9 @@ jobs:
       - name: Output bucket content
         run: |
           echo "I'm in $(pwd) directory"
-          export AWS_ACCESS_KEY_ID=$KEY_ID
-          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
-          export AWS_SECRET_ACCESS_KEY=$ACCESS_KEY
-          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
-          export AWS_DEFAULT_REGION=eu-central-1
-          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
-          aws s3 ls
-          cd dags || (echo "Could not change directory on dags" && exit 1)
-          aws s3 sync . s3://andydagsbucket/$DAGS/ --size-only
+          cd $SOURCE_DAGS_DIR || (echo "Could not change directory on dags" && exit 1)
+          aws s3 sync . s3://$S3_BUCKET_NAME/$TARGET_DAGS_DIR/ --size-only
+
+      - name: List bucket content
+        run: |
+          aws s3 ls s3://$S3_BUCKET_NAME --recursive | awk '{$1=$2=$3=""; print $0}' | sed 's/^[ \t]*//'
