Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,11 +3,11 @@
 name: dispatch_test
 
 env:
-      KEY_ID:          ${{ secrets.AWS_ACCESS_KEY_ID }}
-      ACCESS_KEY:      ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       TARGET_DAGS_DIR: ${{ secrets.DAGS_DIR }}
       SOURCE_DAGS_DIR: dags
-      S3_BUCKET_NAME:  andydagsbucket
+      S3_BUCKET_NAME: andydagsbucket
       
 # Controls when the workflow will run
 on:
@@ -50,7 +50,8 @@ jobs:
       - name: Output bucket content
         run: |
           echo "I'm in $(pwd) directory"
-          cd $SOURCE_DAGS_DIR || (echo "Could not change directory on dags" && exit 1)
+          #cd $SOURCE_DAGS_DIR || (echo "Could not change directory on dags" && exit 1)
+          cd dags || (echo "Could not change directory on dags" && exit 1)
           #aws s3 sync . s3://$S3_BUCKET_NAME/$TARGET_DAGS_DIR/ --size-only
 
       - name: List bucket content
