Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -55,4 +55,5 @@ jobs:
           export AWS_DEFAULT_REGION=eu-central-1
           echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
           aws s3 ls
-          aws s3 sync dags/ s3://andydagsbucket/$DAGS/ --size-only
+          cd dags || (echo "Could not change directory on dags" && exit 1)
+          aws s3 sync . s3://andydagsbucket/$DAGS/ --size-only
