Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -50,8 +50,8 @@ jobs:
       - name: Output bucket content
         run: |
           echo "I'm in $(pwd) directory"
-          #cd $SOURCE_DAGS_DIR || (echo "Could not change directory on dags" && exit 1)
-          cd dags || (echo "Could not change directory on dags" && exit 1)
+          cd $SOURCE_DAGS_DIR || (echo "Could not change directory on dags" && exit 1)
+          #cd dags || (echo "Could not change directory on dags" && exit 1)
           #aws s3 sync . s3://$S3_BUCKET_NAME/$TARGET_DAGS_DIR/ --size-only
 
       - name: List bucket content
